### ISSUE TITLE
React CSS coordination issue

### ISSUE THREAD

**Issue by aainn** [devugees/digital-notice-board#34]

**Comment by aainn** [comment]
Hi peeps. i would like to coordinate the  naming of the side slide components

**Comment by sashseurat** [comment]
Inana: SlideCode.jsx

**Comment by sashseurat** [comment]
Roman: SlidePhotos.jsx

**Comment by sashseurat** [comment]
Mike: SlideVideo.jsx

**Comment by sashseurat** [comment]
Samar: VideoDescription.jsx

**Comment by sashseurat** [comment]
Flu: SlideAnnounement.jsx

**Comment by aainn** [comment]
https://daneden.github.io/animate.css/?
